# Name of the bucket
bucket_name = "my-bucket"
# Region of the bucket
region = "eu-central-1"
# Endpoint of the region (only used for custom regions)
# endpoint = "s3.eu-central-1.amazonaws.com"
endpoint = ""
# S3 access key id
access_key_id = ""
# S3 secret access key
access_key_secret = ""

